# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171027_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='faver_count',
            new_name='favor_count',
        ),
    ]
