# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171027_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ctime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
