# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171027_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='ctime',
        ),
    ]
